MONGO_URI ="mongodb+srv://st5458:Mani2002@cluster0.ttxftbc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
API_KEY = "AIzaSyCTdyerIeb0_fOrlQeCZ2VNB29fqQ2x3Mc"

[postgres]
host = "db.sdkssjyxngxkhebppuog.supabase.co"
port = 5432
database = "postgres"
user = "postgres"
password = "Mani@20026385"



